### PR TITLE
Fix bugs in influence

### LINKED ISSUE #357: ZeroDivisionError in conjugate gradient method
I was running scripts to reproduce the paper "Influence Functions in Deep Learning are Fragile" based on the latest pydvl development version. When I used the conjugate gradient method for solving hvp, I got error message:

```
2023-05-31 16:57:11,280 | mlrc23.influence_utils | INFO | Estimating influence values from optimal model with cg inversion and up influence type, using Hessian regularization of 0.001
Traceback (most recent call last):
  File "/home/murong/IF_new/mlrc23-influence-functions/src/mlrc23/experiments/exp_1_iris.py", line 315, in <module>
    json.dump(metrics, outfile, indent=4)
  File "/home/murong/IF_new/mlrc23-influence-functions/src/mlrc23/experiments/exp_1_iris.py", line 261, in run
    logger.info(
  File "/home/murong/IF_new/mlrc23-influence-functions/src/mlrc23/influence_utils.py", line 273, in compute_influences_train_pydvl
    train_factors = compute_influence_factors(
  File "/home/murong/.cache/pypoetry/virtualenvs/ml-reproducibility-challenge-2023-RNd5E6To-py3.10/lib/python3.10/site-packages/pydvl/influence/general.py", line 73, in compute_influence_factors
    return solve_hvp(
  File "/home/murong/.cache/pypoetry/virtualenvs/ml-reproducibility-challenge-2023-RNd5E6To-py3.10/lib/python3.10/site-packages/pydvl/influence/inversion.py", line 73, in solve_hvp
    return solve_batch_cg(
  File "/home/murong/.cache/pypoetry/virtualenvs/ml-reproducibility-challenge-2023-RNd5E6To-py3.10/lib/python3.10/site-packages/pydvl/influence/frameworks/torch_differentiable.py", line 115, in solve_batch_cg
    bi_cg, _ = solve_cg(reg_hvp, bi, x0=x0, rtol=rtol, atol=atol, maxiter=maxiter)
  File "/home/murong/.cache/pypoetry/virtualenvs/ml-reproducibility-challenge-2023-RNd5E6To-py3.10/lib/python3.10/site-packages/pydvl/influence/frameworks/torch_differentiable.py", line 153, in solve_cg
    alpha = gamma / torch.sum(torch.matmul(p, Ap)).item()
ZeroDivisionError: float division by zero
```

Please find my code [here](https://github.com/appliedAI-Initiative/mlrc23-influence-functions/tree/pydvl_updates)
The [main script](https://github.com/appliedAI-Initiative/mlrc23-influence-functions/blob/pydvl_updates/src/mlrc23/experiments/exp_1_iris.py)
Parameters:
```
influence_functions:
  iris:
    network_hyperparameters:
      network_width:
      - 5
      network_length:
      - 1
      weight_decay:
      - 0.0
    experiment_parameters:
      train_epochs: 60000
      retrain_epochs: 7500
      optimizer: sgd
      optimizer_lr: 0.001
      scheduler:
      model_activation: relu
      train_test_split: 0.8
      top_fraction: 0.166
      inversion_types:
      - cg
      influence_types:
      - up
      repetitions: 1
      hessian_regularization: 0.001
      weight_initializer: xavier_normal
```

### PR DESCRIPTION
**Pull request by Xuzzo**
### Description

This PR closes #357, #356 

### Changes

- Moves break condition up in cg
- adds device in identity_tensor

### Checklist

- [ ] Wrote Unit tests (if necessary)
- [ ] Updated Documentation (if necessary)
- [ ] Updated Changelog
- [ ] If notebooks were added/changed, added boilerplate cells are tagged with `"nbsphinx":"hidden"`

### CODE REVIEW

**Comment by mdbenito** [comment]
@Xuzzo Can you get the checks to pass and merge this? We have #365 almost ready to be merged and it will be affected by whatever you do here. Kristof will then proceed to rewrite some interfaces and should be able to start with a clean slate

**Comment by AnesBenmerzoug** [comment]
@Xuzzo The docs failure is due to a missing appendix section in the [influence imagenet notebook](https://github.com/appliedAI-Initiative/pyDVL/blob/fb3c805e84bde572faaf34c47c1596e90217fd18/notebooks/influence_imagenet.ipynb).

The test failure comes from somewhere else though. I will try to fix that in a separate PR.

**Comment by mdbenito** [comment]
> @Xuzzo The docs failure is due to a missing appendix section in the [influence imagenet notebook](https://github.com/appliedAI-Initiative/pyDVL/blob/fb3c805e84bde572faaf34c47c1596e90217fd18/notebooks/influence_imagenet.ipynb).
> 
> @mdbenito The test failure comes from somewhere else though (It also appears in the develop branch, which is weird). I will try to fix that in a separate PR.

I think @schroedk has suffered the issue as well in https://github.com/appliedAI-Initiative/pyDVL/pull/365

**Comment by mdbenito** [comment]
@Xuzzo In the future, please follow the branch naming conventions!

**Pull request merged**
